### ISSUE TITLE
Cleanup ebutton topics

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/rtt_control_components#11]
Now the new `ebutton_status` topic is used in the dashboard (tue-robotics/dashboard#8), we should cleanup the old topics.

The executives previously listened to the `/amigo/runstop` (`boolean`) topic. Should we continue to provide this?

I think these are the essential topics:
- `ebutton_status`
- `hardware_status`
- `dashboard_ctrlcmds`
- the fuses for the battery value

**Comment by TonPeters** [comment]
Wat mij betreft kunnen alle andere topics idd weg of intern in orocos verwerkt worden. Ik weet echter niet of het runstop topic nog ergens anders in de software wordt afgeluisterd?

**Comment by MaxBaeten** [comment]
Removed

**Comment by MaxBaeten** [comment]
However, not sure about /amigo/emergency_switch

**Comment by Rayman** [comment]
Can this be closed?

**Comment by jlunenburg** [comment]
@Timple , @MaxBaeten : do you know the status of this? Can this be closed?

**Comment by Timple** [comment]
The rgb_lights_manager listens to this topic.

https://github.com/tue-robotics/rgb_lights_manager/issues/2

**Comment by MatthijsBurgh** [comment]
@Timple , @MaxBaeten status?

**Comment by MatthijsBurgh** [comment]
@Timple , @MaxBaeten status?

**Comment by Timple** [comment]
https://github.com/tue-robotics/rgb_lights_manager/issues/2 also close this
