### ISSUE TITLE
Error in AnalogInsGeneric

### ISSUE THREAD

**Issue by svddries** [tue-robotics/rtt_control_components#15]
Directly after starting ahardware (error did not show after restart):

23.779 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.779 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.780 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.780 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.781 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.781 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.782 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.782 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.783 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.783 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.784 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.784 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.785 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.785 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.786 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.786 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.787 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.787 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.788 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1
23.788 [ ERROR  ][Logger] In AnalogInsGeneric: Could not read data for inport beckhoffmsg_in_1

**Comment by MaxBaeten** [comment]
This error is a result from a bug when starting up the hardware. It sometimes cannot find any of the ethercat slaves. I guess thhis is a bug in SOEM. However the fact that AnalogInsGeneric publishes a valid error at 1000Hz makes sure that it is impossible to see what caused the error.
A restart of the hardware will fix this problem but to be sure I will remove these warnings.
