### ISSUE TITLE
Resetting any bodypart does not work

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/rtt_control_components#16]
1. I initiate a grasp
2. I hit the emergency button
3. I resume, and got the following error
    ```
    [ERROR] [1429530067.991758513]: Safety: Error of joint q4 exceeded limit (0.09). jointErrors[3] = 0.098153 output disabled.
    ```
4. The arm will be in error and it will not home or start

**Comment by MaxBaeten** [comment]
This is a bug, but it is a bit different I guess. You have to reset twice for some reason. After resetting twice the arm can be restarted or rehomed.

**Comment by MaxBaeten** [comment]
@Timple, Can you have a look? Shouldn't we build in a reset of the reference generators in jointTrajectory Action?

**Comment by MaxBaeten** [comment]
Part is fixed, part is a different issue in the tue_manipulation
