### ISSUE TITLE
Joint limits should come from URDF model

### ISSUE THREAD

**Issue by Timple** [tue-robotics/rtt_control_components#17]
Joint limits are specified at multiple places, they should come from the URDF model. 

Translation:
minpos = joint->limits->lower
maxpos = joint->limits->upper
maxvel = joint->limits->velocity
maxacc = joint->limits->effort

**Comment by MaxBaeten** [comment]
This is fixed right?

**Comment by Timple** [comment]
Closed by 4d90358b93742ae7fafbdd4ce1a3ce47bc7ddf57

**Comment by Timple** [comment]
Closed by 4d90358b93742ae7fafbdd4ce1a3ce47bc7ddf57
