### ISSUE TITLE
All slaves not operational: No Error

### ISSUE THREAD

**Issue by MaxBaeten** [tue-robotics/rtt_control_components#24]
This has something to do with timing and the supervisor. Trying to solve this by not using always on components. So the previously always on components are now just stared normally.

**Comment by Rayman** [comment]
Is this fixed?

**Comment by MatthijsBurgh** [comment]
@MaxBaeten status?

**Comment by MaxBaeten** [comment]
Status is that the autolaunch from Rein detects this from happening and then relaunches. I do not know where the bug comes from or how to fix it. It has nothing to do with rtt_control_components btw. This is related to the ethercat drivers.

**Comment by MatthijsBurgh** [comment]
@MaxBaeten still an issue or closing?

**Comment by MaxBaeten** [comment]
We can close this, since it is not a prio to fix this since we have a good workaround
