### ISSUE TITLE
Switch all components to ROS logging

### ISSUE THREAD

**Issue by Timple** [tue-robotics/rtt_control_components#34]
Now the hardware is auto-launched we have limited access to the output of the components.

I propose to switch to the ROS logging system.

Pros: 
- Standard ROS debugging tools can be used (swri_console etc)

Cons: 
- All components get 'polluted' with a include ros.h and ROS_INFO etc statements

Logging to ROS is [realtime safe](http://www.orocos.org/forum/orocos/orocos-users/rtt-ros-integration-realtime-safe)

Question:
Would there be an easy way to override the behaviour of 
`log(Error) << "Hello " << "World" << endlog()` 
to 
`ROS_DEBUG_STREAM("Hello " << "World");`
?

**Comment by reinzor** [comment]
Console.h should do it

**Comment by Timple** [comment]
Which console.h?

**Comment by reinzor** [comment]
`<ros/console.h>`

**Comment by Timple** [comment]
I was more looking for a way to modify the behaviour of the orocos version: log(Error) to behave like a ROS_ERROR_STREAM.

This way we do not have to modify our components. And (more important) components not under our maintenance.

Including ros/console.h is easy, but I was hoping to prevent that

**Comment by Timple** [comment]
As a quick workaround we can also use a seperate python node that just reads the orocos.log txt file generated by orocos and output it to ROSLOG :)
